import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {FLOW_STATES,type FlowState,type FlowWorkspaceData} from '@/features/v2/foundations/flowModel';
const block=/^```hermes-flow\r?\n([\s\S]*?)\r?\n```[ \t]*$/gm;
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const conflict=(s:string)=>Object.assign(Error(s),{status:409});
const inside=(root:string,file:string)=>{const rel=path.relative(root,file);return !!rel&&!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel);};
type Manifest={version:1;title:string;root:string;stages:{id:string;title:string;description:string;next:string;status:FlowState;files:{id:string;label:string;path:string}[]}[];history:FlowWorkspaceData['history']};
export function parseFlow(text:string):{manifest:Manifest;start:number;length:number}|null{
 const matches=[...text.matchAll(block)];if(!matches.length)return null;if(matches.length!==1)throw Error('Mehrere Flow-Blöcke in einer Projektnotiz');
 const m=JSON.parse(matches[0][1]) as Manifest;
 if(m.version!==1||typeof m.title!=='string'||!m.title.trim()||m.title.length>180||typeof m.root!=='string'||!path.isAbsolute(m.root)||!Array.isArray(m.stages)||!m.stages.length||m.stages.length>20||!Array.isArray(m.history))throw Error('Flow-Beschreibung unvollständig');
 const ids=new Set<string>();for(const s of m.stages){if(!s||typeof s.id!=='string'||!/^[a-z0-9-]{1,50}$/.test(s.id)||ids.has(s.id)||!Object.hasOwn(FLOW_STATES,s.status)||typeof s.title!=='string'||typeof s.description!=='string'||typeof s.next!=='string'||!Array.isArray(s.files)||s.files.length>20)throw Error('Ungültige Flow-Station');ids.add(s.id);const files=new Set<string>();for(const f of s.files){if(!f||!/^[a-z0-9-]{1,50}$/.test(f.id)||files.has(f.id)||typeof f.label!=='string'||typeof f.path!=='string'||path.isAbsolute(f.path)||f.path.split(/[\\/]/).some(p=>p==='..'||!p)||f.path.includes(':'))throw Error('Ungültiger Flow-Dateiverweis');files.add(f.id);}}
 return {manifest:m,start:matches[0].index!,length:matches[0][0].length};
}
async function note(vault:string,id:string){const root=await fs.realpath(vault);if(typeof id!=='string'||!id.startsWith('05 🚀 Projekte/')||!id.endsWith('.md')||id.includes('\\')||id.split('/').some(p=>!p||p.startsWith('.')||['Code','_Assets'].includes(p)))throw Error('Ungültige Projektnotiz');const base=await fs.realpath(path.join(root,'05 🚀 Projekte'));if(!inside(root,base))throw Error('Projektordner außerhalb');const full=await fs.realpath(path.join(root,id));const stat=await fs.stat(full);if(!inside(base,full)||!stat.isFile()||stat.size>1000000)throw Error('Projektnotiz nicht unterstützt');const text=await fs.readFile(full,'utf8');const parsed=parseFlow(text);if(!parsed)throw Error('Noch kein Produktionsablauf hinterlegt');return {full,text,...parsed};}
const types:Record<string,string>={'.mp4':'video/mp4','.webm':'video/webm','.mp3':'audio/mpeg','.wav':'audio/wav','.ogg':'audio/ogg','.txt':'text/plain','.md':'text/plain','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.pdf':'application/pdf'};
async function artifact(m:Manifest,stage:string,id:string){const s=m.stages.find(s=>s.id===stage),f=s?.files.find(f=>f.id===id);if(!f)throw Error('Datei ist diesem Ablauf nicht zugeordnet');const type=types[path.extname(f.path).toLowerCase()];if(!type)throw Error('Dateiformat nicht unterstützt');const root=await fs.realpath(m.root);const full=await fs.realpath(path.join(root,f.path));if(!inside(root,full))throw Error('Datei außerhalb des freigegebenen Projektordners');const stat=await fs.stat(full);if(!stat.isFile())throw Error('Keine Datei');return {full,size:stat.size,type};}
export async function flowFile(vault:string,project:string,stage:string,id:string){return artifact((await note(vault,project)).manifest,stage,id);}
export async function readFlow(vault:string,project:string):Promise<FlowWorkspaceData>{const {text,manifest:m}=await note(vault,project);return {project,title:m.title,revision:hash(text),history:m.history,stages:await Promise.all(m.stages.map(async s=>({...s,files:await Promise.all(s.files.map(async f=>{const url='/api/vault/flows/file?'+new URLSearchParams({project,stage:s.id,file:f.id});try{const a=await artifact(m,s.id,f.id);return {id:f.id,label:f.label,exists:true,size:a.size,type:a.type,url};}catch{return {id:f.id,label:f.label,exists:false,type:'',url};}}))})))};}
export async function listFlows(vault:string){const flows:FlowWorkspaceData[]=[],issues:string[]=[];const base=path.join(vault,'05 🚀 Projekte');async function walk(dir:string,depth:number){if(depth>6)return;for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||e.name.startsWith('.')||['Code','_Assets'].includes(e.name))continue;const full=path.join(dir,e.name);if(e.isDirectory()){await walk(full,depth+1);continue;}if(!e.name.endsWith('.md')||(await fs.stat(full)).size>1000000)continue;const text=await fs.readFile(full,'utf8');if(!text.includes('```hermes-flow'))continue;const id=path.relative(vault,full).split(path.sep).join('/');try{flows.push(await readFlow(vault,id));}catch(e){issues.push(e instanceof Error?e.message:'Flow konnte nicht gelesen werden');}}}await walk(base,0);return {flows,issues};}
export async function updateFlow(vault:string,input:unknown){const d=input as {project:string;stage:string;status:FlowState;reason:string;revision:string};if(!d||typeof d.project!=='string'||typeof d.reason!=='string'||!d.reason.trim()||d.reason.length>2000||!Object.hasOwn(FLOW_STATES,d.status)||!/^\w{64}$/.test(d.revision))throw Error('Status und Begründung prüfen');const initial=await note(vault,d.project),lock=initial.full+'.hermes-lock';let handle;try{handle=await fs.open(lock,'wx');}catch{throw conflict('Projekt wird gerade bearbeitet. Bitte später neu laden.');}
 try{const n=await note(vault,d.project);if(n.full!==initial.full||hash(n.text)!==d.revision)throw conflict('Die Projektnotiz wurde geändert. Bitte neu laden.');const s=n.manifest.stages.find(s=>s.id===d.stage);if(!s)throw Error('Station fehlt');if(s.status===d.status)throw Error('Status ist unverändert');n.manifest.history.push({at:new Date().toISOString(),stage:s.id,from:s.status,to:d.status,reason:d.reason.trim()});s.status=d.status;const nl=n.text.includes('\r\n')?'\r\n':'\n';const replacement=('```hermes-flow\n'+JSON.stringify(n.manifest,null,2)+'\n```').replace(/\n/g,nl);const after=n.text.slice(0,n.start)+replacement+n.text.slice(n.start+n.length);
 const backups=path.join(path.dirname(n.full),'.hermes-history');await fs.mkdir(backups,{recursive:true});if((await fs.lstat(backups)).isSymbolicLink())throw Error('Sicherungsordner nicht unterstützt');await fs.writeFile(path.join(backups,path.basename(n.full)+'.'+d.revision+'.md'),n.text,{encoding:'utf8',flag:'wx'}).catch(e=>{if(e.code!=='EEXIST')throw e;});if(hash(await fs.readFile(n.full,'utf8'))!==d.revision)throw conflict('Projekt wurde während des Speicherns geändert');const temp=n.full+'.'+randomUUID()+'.tmp';await fs.writeFile(temp,after,{encoding:'utf8',flag:'wx'});try{await fs.rename(temp,n.full);}finally{await fs.unlink(temp).catch(()=>{});}return {ok:true,flow:await readFlow(vault,d.project)};
 }finally{await handle.close();await fs.unlink(lock);}
}
