"use client";
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {STORAGE,candidates,demoImpulses,emptyLab,formOf,parseLab,tagsFrom,withEvent,type Lab} from './model';
import './atelier.css';
const ImpulseScene=dynamic(()=>import('./ImpulseScene'),{ssr:false});
export default function AtelierLab(){
 const [lab,setLab]=useState<Lab>(emptyLab);const [ready,setReady]=useState(false);const [locked,setLocked]=useState(false);const [status,setStatus]=useState('Testspeicher wird geöffnet …');
 const [selected,setSelected]=useState<string|null>(null);const [panel,setPanel]=useState(true);const [composer,setComposer]=useState(false);const [history,setHistory]=useState(false);const [raw,setRaw]=useState('');const [origin,setOrigin]=useState('');const [tags,setTags]=useState('');const [answer,setAnswer]=useState('');const [test,setTest]=useState('');const [scanning,setScanning]=useState(false);const [reset,setReset]=useState(0);const [quiet,setQuiet]=useState(false);const [sound,setSound]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const audio=useRef<AudioContext|null>(null);
 const active=lab.impulses.find(i=>i.id===selected);const links=lab.links.filter(l=>l.status!=='rejected'&&(l.a===selected||l.b===selected));
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE);if(saved)setLab(parseLab(saved));setStatus(saved?'Teststand wiederhergestellt':'Bereit · eigener Testspeicher');}catch{setLocked(true);setStatus('Testspeicher nicht lesbar. Bestehende Daten werden nicht überschrieben. Exportiere sie zur Sicherung.');}setQuiet(window.matchMedia('(prefers-reduced-motion: reduce)').matches);setReady(true);return()=>{if(timer.current)clearTimeout(timer.current);void audio.current?.close();};},[]);
 function commit(next:Lab){if(locked||!ready)return false;try{localStorage.setItem(STORAGE,JSON.stringify(next));setLab(next);setStatus('Lokal gespeichert · '+new Date().toLocaleTimeString('de-DE'));return true;}catch{setStatus('Speichern fehlgeschlagen. Änderung nicht übernommen; bitte Testspeicher prüfen.');return false;}}
 function tone(kind:'pick'|'link'|'shape'|'scan',force=false){const ctx=audio.current;if(!ctx||ctx.state!=='running'||(!sound&&!force))return;const now=ctx.currentTime;const frequencies=kind==='shape'?[196,294,392]:kind==='link'?[440,660]:kind==='scan'?[110,220]:[330];frequencies.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(f*(kind==='scan'?2:1.01),now+.5);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.025/frequencies.length,now+.05+i*.025);g.gain.exponentialRampToValueAtTime(.0001,now+1.1);o.connect(g);g.connect(ctx.destination);o.start(now);o.stop(now+1.2);o.onended=()=>{o.disconnect();g.disconnect();};});if(kind==='scan'){const buffer=ctx.createBuffer(1,ctx.sampleRate*.65,ctx.sampleRate);const values=buffer.getChannelData(0);for(let i=0;i<values.length;i++)values[i]=(Math.random()*2-1)*.12;const n=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();n.buffer=buffer;filter.type='highpass';filter.frequency.value=3400;g.gain.setValueAtTime(.1,now);g.gain.exponentialRampToValueAtTime(.001,now+.6);n.connect(filter);filter.connect(g);g.connect(ctx.destination);n.start();n.onended=()=>{n.disconnect();filter.disconnect();g.disconnect();};}}
 async function toggleSound(){if(sound){setSound(false);await audio.current?.suspend();return;}try{audio.current??=new AudioContext();await audio.current.resume();setSound(true);tone('pick',true);}catch{setStatus('Audio konnte nicht aktiviert werden.');}}
 function pick(id:string){setSelected(id);setAnswer(lab.impulses.find(i=>i.id===id)?.answer??'');setTest('');setPanel(true);setComposer(false);setHistory(false);tone('pick');}
 function add(){if(!raw.trim()||lab.impulses.length>=300)return;const id=crypto.randomUUID();const impulse={id,raw:raw.trim(),origin:origin.trim(),tags:tagsFrom(tags),created:new Date().toISOString(),example:false,answer:'',question:'Was könnte daraus werden — und was bleibt noch offen?',clear:false,resting:false};if(!commit(withEvent({...lab,impulses:[...lab.impulses,impulse]},'Impuls erfasst',id,impulse.raw)))return;setSelected(id);setAnswer('');setRaw('');setOrigin('');setTags('');setComposer(false);setPanel(true);tone('pick');}
 function scan(){if(!active||scanning||locked)return;const found=candidates(lab,active.id);commit(withEvent({...lab,links:[...lab.links,...found]},'Zusammenhänge gesucht',active.id,`${found.length} neue Vorschläge anhand gemeinsamer Stichwörter. Keine KI-Abfrage.`));setScanning(true);tone('scan');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setScanning(false),quiet?100:1800);}
 function resolve(id:string,confirmed:boolean){const edge=lab.links.find(l=>l.id===id);if(!edge)return;commit(withEvent({...lab,links:lab.links.map(l=>l.id===id?{...l,status:confirmed?'confirmed':'rejected'}:l)},confirmed?'Verbindung bestätigt':'Vorschlag verworfen',active?.id??'',edge.reason));tone('link');}
 function shape(){if(!active||!answer.trim())return;commit(withEvent({...lab,impulses:lab.impulses.map(i=>i.id===active.id?{...i,answer:answer.trim(),clear:false}:i)},'Formung festgehalten',active.id,answer.trim()));tone('shape');}
 function exportData(){const blob=new Blob([locked?(localStorage.getItem(STORAGE)??''):JSON.stringify(lab,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Hermes-Ideenatelier-Teststand.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importData(file:File|undefined){if(!file)return;try{if(file.size>8_000_000)throw Error('Datei ist zu groß.');const incoming=parseLab(await file.text());if(lab.impulses.length||locked){setStatus('Import nur in einen leeren, lesbaren Testspeicher möglich. Dein vorhandener Stand bleibt erhalten.');return;}commit(withEvent(incoming,'Testsicherung importiert','',file.name));}catch(e){setStatus(e instanceof Error?e.message:'Import nicht lesbar.');}}
 const disabled=!ready||locked;
 return <main className="atelier-lab">
  <div className="atelier-canvas"><ImpulseScene lab={lab} selected={selected} scanning={scanning} quiet={quiet} onPick={pick} reset={reset}/></div>
  <header className="atelier-header"><div><span className="atelier-kicker">HERMES3D · ISOLIERTER TESTRAUM</span><h1>Neuronales Impulsfeld</h1><p>Ein Gedanke darf erst einmal ein Gedanke sein.</p></div><a href="http://localhost:3464/v2" target="_blank" rel="noreferrer">Original öffnen ↗</a></header>
  <nav className="atelier-toolbar" aria-label="Atelier Werkzeuge"><button onClick={()=>{setComposer(true);setHistory(false);setPanel(true);}} disabled={disabled}>＋ Impuls</button><button onClick={()=>{setHistory(!history);setPanel(true);}}>Entstehung</button><button onClick={()=>setReset(r=>r+1)}>Überblick</button><button onClick={()=>setQuiet(!quiet)} aria-pressed={quiet}>{quiet?'Bewegung ruhig':'Bewegung an'}</button><button onClick={()=>void toggleSound()} aria-pressed={sound}>{sound?'Ton an':'Ton aktivieren'}</button></nav>
  <div className="atelier-guide"><span>IDEENATELIER / VERSUCH 01</span><h2>{scanning?'Verbindungen suchen …':active?formOf(lab,active.id):'Hier beginnt etwas.'}</h2><p>{scanning?'Der Scan vergleicht die Stichwörter. Seine Vorschläge bleiben anschließend sichtbar.':active?'Wähle eine Verbindung. Kläre eine Frage. Beobachte, wie der Gedanke Form annimmt.':'Erfasse einen eigenen Impuls oder erkunde das gekennzeichnete Beispiel. Ziehen dreht den Raum, Scrollen verändert die Nähe.'}</p>{!lab.impulses.length&&<button className="atelier-primary" disabled={disabled} onClick={()=>{const examples=demoImpulses();commit(withEvent({...lab,impulses:examples},'Beispiel geladen','','Sechs Anschauungsimpulse, keine neuen LifeOS-Einträge.'));setSelected(examples[0].id);setPanel(true);}}>Beispiel erkunden</button>}<small role="status">{status}</small></div>
  <aside className="atelier-index" aria-label="Impulse auswählen">{lab.impulses.map(i=><button key={i.id} onClick={()=>pick(i.id)} aria-pressed={selected===i.id}><i/>{i.raw}<small>{i.example?'BEISPIEL · ':''}{i.resting?'ruhend':formOf(lab,i.id)}</small></button>)}</aside>
  {(active||composer||history)&&(!panel?<button className="atelier-restore" onClick={()=>setPanel(true)}>↗ Arbeitsfläche öffnen</button>:<aside className="atelier-panel" aria-label="Atelier Arbeitsfläche"><div className="atelier-panel-tools"><span>{history?'Entstehung':composer?'Neuer Impuls':'Gedanken formen'}</span><button aria-label="Arbeitsfläche minimieren" onClick={()=>setPanel(false)}>—</button><button aria-label="Arbeitsfläche schließen" onClick={()=>{setPanel(false);setComposer(false);setHistory(false);}}>×</button></div>
   {history?<><h2>Wie es entstanden ist</h2><p>Aufgezeichnete Handlungen in diesem Test. Keine rekonstruierte Vorgeschichte.</p><ol className="atelier-history">{[...lab.events].reverse().map(e=><li key={e.id}><small>{new Date(e.at).toLocaleString('de-DE')}</small><strong>{e.action}</strong><p>{e.detail}</p></li>)}</ol></>:composer?<><h2>Festhalten genügt.</h2><label>Dein Gedanke<textarea maxLength={2000} value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Da könnte etwas sein …"/></label><label>Was hat ihn ausgelöst? <small>optional</small><input maxLength={500} value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="Eine Erinnerung, ein Bild, ein Gespräch"/></label><label>Stichwörter für Verbindungen<input maxLength={500} value={tags} onChange={e=>setTags(e.target.value)} placeholder="z. B. technik, dokumentation, portfolio"/></label><button className="atelier-primary" disabled={disabled||!raw.trim()||lab.impulses.length>=300} onClick={add}>Impuls festhalten</button><small>Bleibt im Testspeicher dieser Browseradresse. Es entsteht kein Projekt.</small></>:active&&<>
    <span className="atelier-kicker">{active.example?'ANSCHAUUNGSBEISPIEL':'DEIN TESTIMPULS'} · {formOf(lab,active.id)}</span><h2>{active.raw}</h2><p>{active.origin||'Kein Auslöser angegeben.'}</p><div className="atelier-tags">{active.tags.map(t=><span key={t}>{t}</span>)}</div>
    <section><h3>Jarvis · Zusammenhänge</h3><p>Dieser Test vergleicht Stichwörter lokal. Er ruft kein KI-Modell auf.</p><button className="atelier-primary" onClick={scan} disabled={disabled||scanning}>{scanning?'Scan läuft …':'Verbindungen suchen'}</button>{!links.length&&<small>Noch keine sichtbaren Verbindungen. Gemeinsame Stichwörter ermöglichen Vorschläge.</small>}{links.map(l=>{const other=lab.impulses.find(i=>i.id===(l.a===active.id?l.b:l.a));return <article className="atelier-edge" key={l.id}><strong>{other?.raw}</strong><small>{l.status==='confirmed'?'BESTÄTIGTE SYNAPSE':'VORSCHLAG'}</small><p>{l.reason.replace(' Eine mögliche Beziehung, noch nicht bestätigt.', '')}</p>{l.status==='candidate'?<div><button disabled={disabled} onClick={()=>resolve(l.id,true)}>Verbindung bestätigen</button><button disabled={disabled} onClick={()=>resolve(l.id,false)}>Verwerfen</button></div>:<button onClick={()=>other&&pick(other.id)}>Zum verbundenen Impuls →</button>}</article>;})}</section>
    <section><h3>Hermes · Weiterdenken</h3><label>{active.question}<textarea value={answer} maxLength={4000} onChange={e=>setAnswer(e.target.value)} placeholder="Eine mögliche Richtung — keine Verpflichtung."/></label><button disabled={disabled||!answer.trim()} onClick={shape}>Gedanken festhalten & Form entwickeln</button><small>Die Form zeigt deinen dokumentierten Entwurf, keine automatische Qualitätsbewertung.</small>{active.answer&&!active.clear&&<button onClick={()=>{commit(withEvent({...lab,impulses:lab.impulses.map(i=>i.id===active.id?{...i,clear:true}:i)},'Als klar genug markiert',active.id,'Bewusste Testentscheidung; kein Projekt angelegt.'));tone('shape');}} disabled={disabled}>Für mich ist die Idee jetzt klar genug</button>}</section>
    <section><h3>Kleines Experiment skizzieren</h3><label>Welche Unsicherheit soll ein kleiner Versuch klären?<textarea maxLength={2000} value={test} onChange={e=>setTest(e.target.value)} placeholder="Eine Frage, ein kleiner Test, ein erkennbares Ergebnis."/></label><button disabled={disabled||!test.trim()} onClick={()=>{if(commit(withEvent(lab,'Experiment skizziert',active.id,test.trim()))){setTest('');tone('shape');}}}>Testfrage speichern</button><small>Speichert die Skizze in der Entstehung. Startet keinen Agenten und keine Programmausführung.</small></section>
    <button onClick={()=>commit(withEvent({...lab,impulses:lab.impulses.map(i=>i.id===active.id?{...i,resting:!i.resting}:i)},active.resting?'Impuls wieder aufgenommen':'Impuls ruht',active.id,active.raw))} disabled={disabled}>{active.resting?'Wieder aufnehmen':'Ruhen lassen'}</button>
   </>}
  </aside>)}
  <footer className="atelier-footer"><span>Gestrichelt: Vorschlag · Lila: bestätigt · Formen zeigen deine Bearbeitung</span><div><button disabled={!ready} onClick={exportData}>Testsicherung exportieren</button><label className="atelier-import">Sicherung laden<input type="file" accept="application/json,.json" onChange={e=>void importData(e.target.files?.[0])}/></label></div></footer>
 </main>;
}
