"use client";
import {useState} from 'react';
import type {MemoryCatalog} from './memoryCatalog';
export function MemoryManager({catalog,topic,phase,ready,onSave,onTopic}:{catalog:MemoryCatalog;topic:string;phase:string;ready:boolean;onSave:(c:MemoryCatalog)=>Promise<boolean>;onTopic:(id:string)=>void}){
 const [name,setName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const realm=catalog.realms.find(r=>r.id===topic),album=realm?.albums.find(a=>a.id===phase);
 async function edit(kind:'world'|'album'|'rename-world'|'rename-album'|'archive-world'|'archive-album'|'inward'|'outward',restore?:{world:string;album?:string}){
 if(busy||!ready)return;const title=name.trim();if(!restore&&!kind.startsWith('archive')&&!['inward','outward'].includes(kind)&&!title){setMessage('Bitte einen Namen eingeben.');return;}
 const next=structuredClone(catalog),r=next.realms.find(r=>r.id===topic);let select='';
 if(restore){const target=next.realms.find(r=>r.id===restore.world);if(target){target.archived=false;if(restore.album){const a=target.albums.find(a=>a.id===restore.album);if(a)a.archived=false;}}}
 else if(kind==='world'){if(next.realms.length>=100){setMessage('Maximal 100 Welten.');return;}select=crypto.randomUUID();next.realms.push({id:select,title,color:['#83d7dc','#dbabd1','#e9b47a','#acd3ab'][next.realms.length%4],albums:[]});}
 else if(r){if(kind==='inward'||kind==='outward'){const at=r.albums.findIndex(a=>a.id===phase),to=at+(kind==='inward'?-1:1);if(at>=0&&to>=0&&to<r.albums.length)[r.albums[at],r.albums[to]]=[r.albums[to],r.albums[at]];}if(kind==='album'){if(r.albums.length>=100){setMessage('Maximal 100 Ringe pro Welt.');return;}r.albums.push({id:crypto.randomUUID(),title});}if(kind==='rename-world')r.title=title;if(kind==='rename-album'){const a=r.albums.find(a=>a.id===phase);if(a)a.title=title;}if(kind==='archive-world'){r.archived=true;select=next.realms.find(r=>!r.archived)?.id||'';}if(kind==='archive-album'){const a=r.albums.find(a=>a.id===phase);if(a)a.archived=true;}}
 setBusy(true);try{if(await onSave(next)){setName('');setMessage(restore?'Wiederhergestellt.':kind.startsWith('archive')?'Im Archiv. Alle Fotos bleiben erhalten.':'Gespeichert.');if(select)onTopic(select);}}finally{setBusy(false);}
 }
 return <details className="memory-manager"><summary>Welten & Ringe gestalten</summary><p>Ein Saturn ist deine Welt. Jeder Ring ist ein frei benanntes Album.</p><label>Name<input aria-label="Name für Welt oder Ring" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="z. B. Reisen oder Japan 2026"/></label><fieldset disabled={busy||!ready}><button onClick={()=>void edit('world')}>＋ Saturn erstellen</button><button disabled={!realm||realm.archived} onClick={()=>void edit('album')}>＋ Ring erstellen</button><button disabled={!realm} onClick={()=>void edit('rename-world')}>Saturn umbenennen</button><button disabled={!album} onClick={()=>void edit('rename-album')}>Ring umbenennen</button><button disabled={!album} onClick={()=>void edit('inward')}>Ring nach innen</button><button disabled={!album} onClick={()=>void edit('outward')}>Ring nach außen</button><button disabled={!realm||realm.archived} onClick={()=>void edit('archive-world')}>Saturn ins Archiv entfernen</button><button disabled={!album||album.archived} onClick={()=>void edit('archive-album')}>Ring ins Archiv entfernen</button></fieldset><small>Entfernen blendet aus und bewahrt alle Medien. Namen und Zuordnungen bleiben wie deine Fotos in diesem Browser gespeichert.</small>{message&&<p role="status">{message}</p>}<details><summary>Archiv wiederherstellen</summary>{catalog.realms.map(r=><div key={r.id}>{r.archived&&<button disabled={busy||!ready} onClick={()=>void edit('world',{world:r.id})}>{r.title} wiederherstellen</button>}{r.albums.filter(a=>a.archived).map(a=><button key={a.id} disabled={busy||!ready} onClick={()=>void edit('album',{world:r.id,album:a.id})}>{r.title} · {a.title} wiederherstellen</button>)}</div>)}</details></details>;
}
