import {parseCatalog,type MemoryCatalog} from './memoryCatalog';
export type StoredPhoto={id:string;title:string;phase:string;topic?:string;kind:'image'|'video';blob:Blob};
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('hermes-memory-media',2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('media'))request.result.createObjectStore('media',{keyPath:'id'});if(!request.result.objectStoreNames.contains('settings'))request.result.createObjectStore('settings');};request.onblocked=()=>reject(Error('Bitte weitere Hermes-Tabs schließen und erneut laden.'));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function loadPhotos():Promise<StoredPhoto[]>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('media','readonly');const request=tx.objectStore('media').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();tx.onabort=()=>{db.close();reject(tx.error);};});}
export async function storePhotos(photos:StoredPhoto[]){const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('media','readwrite');photos.forEach(photo=>tx.objectStore('media').put(photo));tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>{db.close();reject(tx.error);};tx.onerror=()=>{db.close();reject(tx.error);};});}
export function fitPhoto(width:number,height:number,maxWidth=4.1,maxHeight=2.2):[number,number]{if(width<=0||height<=0)return[maxWidth,maxHeight];const scale=Math.min(maxWidth/width,maxHeight/height);return[width*scale,height*scale];}

export async function loadMemoryCatalog():Promise<MemoryCatalog|null>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('settings','readonly');const request=tx.objectStore('settings').get('catalog');let result:MemoryCatalog|null=null;request.onsuccess=()=>{try{result=request.result?parseCatalog(request.result):null;}catch(e){reject(e);}};tx.oncomplete=()=>{db.close();resolve(result);};tx.onabort=()=>{db.close();reject(tx.error);};});}
export async function saveMemoryCatalog(catalog:MemoryCatalog,expected:MemoryCatalog|null){parseCatalog(catalog);const db=await database();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('settings','readwrite'),store=tx.objectStore('settings'),read=store.get('catalog');read.onsuccess=()=>{if(JSON.stringify(read.result??null)!==JSON.stringify(expected)){tx.abort();return;}store.put(catalog,'catalog');};tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>{db.close();reject(tx.error??Error('Erinnerungsstruktur wurde zwischenzeitlich geändert.'));};});}
