"use client";
/* eslint-disable @next/next/no-img-element -- Local allowlisted source images are shown without third-party transformation. */
import {createContext,useCallback,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {FLOW_STATES,selectedFlow,flowSelection,type FlowWorkspaceData,type FlowState,type FlowFile} from './flowModel';
import {useWorlds} from './WorldsProvider';
import './flow.css';
type Data={flows:FlowWorkspaceData[];error:string;loading:boolean;refresh:()=>Promise<void>;replace:(flow:FlowWorkspaceData)=>void};
const Context=createContext<Data|null>(null);
export function FlowProvider({world,children}:{world:string;children:ReactNode}){
 const [flows,setFlows]=useState<FlowWorkspaceData[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);const sequence=useRef(0);
 const refresh=useCallback(async()=>{const seq=++sequence.current;setLoading(true);try{const r=await fetch('/api/vault/flows');const d=await r.json();if(!r.ok)throw Error(d.error);if(seq!==sequence.current)return;setFlows(d.flows);setError(d.issues.join(' · '));}catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:'Ablauf nicht verfügbar');}finally{if(seq===sequence.current)setLoading(false);}},[]);
 const invalidate=useCallback(()=>{sequence.current++;},[]);
 useEffect(()=>{if(world==='flow')void refresh();return invalidate;},[world,refresh,invalidate]);
 const replace=useCallback((flow:FlowWorkspaceData)=>setFlows(old=>old.map(f=>f.project===flow.project?flow:f)),[]);
 return <Context.Provider value={{flows,error,loading,refresh,replace}}>{children}</Context.Provider>;
}
export function useFlowWorkspace(){const data=useContext(Context);if(!data)throw Error('FlowProvider fehlt');const {selected}=useWorlds();const selection=selectedFlow(selected);const flow=selection?data.flows.find(f=>f.project===selection.project):selected&&!selected.startsWith('run:')?data.flows.find(f=>f.project===selected):data.flows[0];return {...data,flow,stage:flow?.stages.find(s=>s.id===selection?.stage)};}
function Preview({file}:{file:FlowFile}){const [text,setText]=useState('Wird geladen …');useEffect(()=>{if(file.type!=='text/plain')return;const abort=new AbortController();if((file.size??0)>500000)return;fetch(file.url,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.text();}).then(setText).catch(()=>{if(!abort.signal.aborted)setText('Vorschau nicht verfügbar');});return()=>abort.abort();},[file]);return <div className="flow-preview">{file.type.startsWith('video/')?<video src={file.url} controls preload="metadata" playsInline/>:file.type.startsWith('audio/')?<audio src={file.url} controls preload="metadata"/>:file.type.startsWith('image/')?<img src={file.url} alt={file.label}/>:file.type==='application/pdf'?<iframe title={file.label} src={file.url}/>:<pre>{(file.size??0)>500000?'Für die Vorschau zu groß. Bitte die Originaldatei öffnen.':text}</pre>}<a href={file.url} target="_blank" rel="noreferrer">Originaldatei öffnen ↗</a></div>;}
function StageEditor({flow,stageId}:{flow:FlowWorkspaceData;stageId:string}){const stage=flow.stages.find(s=>s.id===stageId)!;const {replace,refresh}=useFlowWorkspace();const [status,setStatus]=useState<FlowState>(stage.status),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const saving=useRef(false);const [revision]=useState(flow.revision);const save=async()=>{if(saving.current)return;saving.current=true;setBusy(true);setMessage('');try{const r=await fetch('/api/vault/flows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:flow.project,stage:stageId,status,reason,revision})});const d=await r.json();if(!r.ok)throw Error(d.error);replace(d.flow);}catch(e){setMessage(e instanceof Error?e.message:'Speichern fehlgeschlagen');}finally{saving.current=false;setBusy(false);}};return <details className="flow-editor"><summary>Status festhalten</summary><p>Deine Prüfung wird in derselben Projektnotiz dokumentiert.</p><label>Neuer Stand<select value={status} onChange={e=>setStatus(e.target.value as FlowState)}>{Object.entries(FLOW_STATES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Was wurde geprüft oder was fehlt?<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="Zum Beispiel: Ton vollständig angehört, Aussprache an zwei Stellen noch korrigieren."/></label><button disabled={busy||status===stage.status||!reason.trim()} onClick={()=>void save()}>{busy?'Wird gespeichert …':'In Obsidian festhalten'}</button>{message&&<><p role="alert">{message}</p><button disabled={busy} onClick={()=>void refresh()}>Aktuellen Stand neu laden</button></>}</details>;}
export function FlowWorkspace({onRead}:{onRead:(path:string)=>void}){
 const {flow,stage,flows,error,loading,refresh}=useFlowWorkspace();const {choose,travel,jobs,flowStatus,selected}=useWorlds();const [preview,setPreview]=useState<FlowFile|null>(null);
 const select=(id:string)=>{choose(id);setPreview(null);};const current=stage??flow?.stages[0];
 return <div className="flow-workspace">
 <label className="flow-project-label">Produktionsablauf<select value={flow?.project??''} onChange={e=>select(e.target.value)}><option value="" disabled>Ablauf wählen</option>{flows.map(f=><option key={f.project} value={f.project}>{f.title}</option>)}</select></label>
 {loading&&<p role="status">Projektstand wird gelesen …</p>}{error&&<p role="alert">{error}</p>}
 {!loading&&!flow&&<p>Für dieses Projekt ist noch kein Ablauf hinterlegt. Wähle einen vorhandenen Produktionsablauf.</p>}
 {flow&&<><div className="flow-caption"><span>DEINE PRODUKTION</span><strong>{flow.title}</strong><small>{flow.stages.filter(s=>s.status==='fertig').length} von {flow.stages.length} Stationen bestätigt · keine automatische Ausführung</small></div>
 <details className="flow-station-picker"><summary>Stationen wechseln · {flow.stages.length}</summary><nav className="flow-stages" aria-label="Produktionsstationen">{flow.stages.map((s,i)=><button key={s.id} aria-pressed={current?.id===s.id} onClick={()=>select(flowSelection(flow.project,s.id))}><b>{String(i+1).padStart(2,'0')}</b><span>{s.title}<small>{FLOW_STATES[s.status]}</small></span><span aria-hidden="true">{s.status==='fertig'?'✓':'↗'}</span></button>)}</nav></details><button onClick={()=>{select(flow.project);window.dispatchEvent(new Event('hermes:flow-overview'));}}>Gesamten Ablauf ansehen ↗</button>
 {current&&<section key={flow.project+'#'+current.id} className="flow-station-detail"><span className="flow-kicker">STATION {flow.stages.indexOf(current)+1} · {FLOW_STATES[current.status]}</span><h2>{current.title}</h2><p>{current.description}</p><div className="flow-next"><small>NÄCHSTER SCHRITT</small><p>{current.next}</p></div><h3>Arbeitsdateien</h3>{!current.files.length&&<p>Noch keine fertigen Dateien zugeordnet.</p>}{current.files.map(f=><button key={f.id} disabled={!f.exists} onClick={()=>setPreview(f)}>{f.label}<small>{f.exists?'Vorhanden · '+((f.size??0)<1048576?Math.max(1,Math.round((f.size??0)/1024))+' KB':((f.size??0)/1048576).toFixed(1)+' MB'):'Nicht verfügbar'}</small></button>)}<small>Eine vorhandene Datei ist kein Nachweis einer abgeschlossenen Prüfung.</small>
 {preview&&current.files.some(f=>f.url===preview.url)&&<><button onClick={()=>setPreview(null)}>Vorschau schließen ×</button><Preview key={preview.url} file={preview}/></>}
 <StageEditor key={flow.revision+current.id} flow={flow} stageId={current.id}/>
 {flow.history.filter(h=>h.stage===current.id).length>0&&<details><summary>Dokumentierter Verlauf</summary>{flow.history.filter(h=>h.stage===current.id).slice(-10).reverse().map((h,i)=><p key={h.at+i}><small>{new Date(h.at).toLocaleString('de-DE')} · {FLOW_STATES[h.to]}</small>{h.reason}</p>)}</details>}
 </section>}
 <div className="flow-source-actions"><button onClick={()=>onRead(flow.project)}>Projektnotiz im Raum lesen ↗</button><button onClick={()=>travel('projects',flow.project,'Zurück zum Projektplaneten')}>◎ Zum Projektplaneten</button></div></>}
 <button onClick={()=>void refresh()} disabled={loading}>Dateien und Stand aktualisieren</button>
 <details className="flow-live"><summary>Unabhängige Hermes-Aufträge · {jobs.length}</summary><p>{flowStatus}</p><small>Diese gemeldeten Aufträge sind dem Produktionsablauf nicht automatisch zugeordnet.</small>{jobs.map(j=><button key={j.id} aria-pressed={selected==='run:'+j.id} onClick={()=>choose('run:'+j.id)}>{j.name}<small>{j.state?.runningAtMs?'Läuft':j.enabled?'Geplant':'Pausiert'}</small>{selected==='run:'+j.id&&<span>{j.state?.lastError||j.description||'Keine weitere Beschreibung gemeldet.'}</span>}</button>)}</details>
 </div>;
}
