export type GoalDraft={title:string;why:string;measure:string;due:string;groups:string[];importance:string;firstStep:string;links:string[];actions:string[];dialogue:string};
export const EMPTY_GOAL:GoalDraft={title:'',why:'',measure:'',due:'',groups:[],importance:'',firstStep:'',links:[],actions:[],dialogue:''};
export function validateGoalDraft(value:unknown):GoalDraft{
 if(!value||typeof value!=='object')throw Error('Zielangaben fehlen');const d=value as Record<string,unknown>;const result={...EMPTY_GOAL};
 for(const key of ['title','why','measure','due','importance','firstStep','dialogue'] as const){if(typeof d[key]!=='string'||d[key].length>(key==='dialogue'?6000:2000))throw Error('Ungültige Zielangaben');result[key]=d[key].trim();}
 if(result.title.length<3||result.title.length>160||/[\r\n]/.test(result.title))throw Error('Bitte einen Zieltitel mit 3–160 Zeichen angeben');
 for(const key of ['groups','links','actions'] as const){if(!Array.isArray(d[key])||d[key].length>30||d[key].some((v:unknown)=>typeof v!=='string'||v.length>400||/[\r\n]/.test(v)))throw Error('Ungültige Verknüpfungen');result[key]=[...new Set(d[key] as string[])];}
 if(result.groups.some(g=>!['beruflich','lernen','familiär','gesundheit','spirituell'].includes(g)))throw Error('Unbekannter Lebensbereich');
 if(result.importance&&!['klein','mittel','gross'].includes(result.importance))throw Error('Ungültige Bedeutung');
 if(result.due){if(!/^\d{4}(-\d{2}){0,2}$/.test(result.due))throw Error('Zeit als Jahr, Jahr-Monat oder Datum angeben');const [y,m,d]=result.due.split('-').map(Number);if((result.due.length>=7&&(m<1||m>12))||(result.due.length===10&&(d<1||new Date(Date.UTC(y,m-1,d)).getUTCMonth()!==m-1)))throw Error('Ungültiger Termin');}
 return result;
}
export function goalFilename(title:string){const clean=title.replace(/[\[\]#\\/:*?"<>|\x00-\x1f]/g,' ').replace(/\.{2,}/g,' ').replace(/\s+/g,' ').trim().replace(/[ .]+$/,'').slice(0,110);if(!clean||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(clean))throw Error('Bitte einen anderen Zieltitel verwenden');return clean+'.md';}
export function goalMarkdown(d:GoalDraft,day:string){const q=JSON.stringify;return ['---','status: entwurf','quelle: Direkte bestätigte Eingabe in Hermes3D','erfasst_am: '+day,'zeitbezug: '+day,'sensibilität: persönlich','ziel: '+q(d.title),'zustand: '+(d.measure?'aktiv':'unklar'),'sternbild: '+q(d.groups),'handlungen: '+q(d.actions),...(d.importance?['bedeutung: '+d.importance]:[]),...(d.due?['frist: '+q(d.due)]:[]),...(d.measure?['messgroesse: '+q(d.measure)]:[]),'---','','## Zielbild','',d.why||'Warum und Zielbild noch offen.','','## Erfolg erkennen','',d.measure||'Erfolgskriterium noch offen.','','## Meilensteine','',...(d.firstStep?['| Nr. | Meilenstein | Termin | Zustand |','| --- | --- | --- | --- |','| 1 | '+d.firstStep.replace(/[|\r\n]/g,' ')+' | offen | offen |']:['Noch keine Meilensteine festgelegt.']),'','## Verbindungen','',...d.links.map(l=>'[['+l.replace(/\.md$/,'')+']]'),'','## Unterstützende Handlungen','',...d.actions.map(a=>'- '+a),'','Handlungen unterstützen dieses Ziel. Eine Erledigung bestätigt nicht automatisch die Zielerreichung.','','## Klärungsgespräch','',d.dialogue||'Keine zusätzlichen KI-Rückfragen dokumentiert.',''].join('\n');}
