"use client";
import {useState} from 'react';
import {PanelWindow} from '../hud/PanelWindow';
import {DIRECTIONS} from './goalLayout';
import {EMPTY_GOAL,type GoalDraft,goalMarkdown} from './goalDraft';
import {HORIZON_ROUTINES} from './horizonRoutines';
import {useWorlds} from './WorldsProvider';
export function GoalComposer({onClose}:{onClose:()=>void}){
 const {objects,refresh,choose}=useWorlds();const [draft,setDraft]=useState<GoalDraft>({...EMPTY_GOAL});const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[questions,setQuestions]=useState(''),[reply,setReply]=useState('');
 const change=(key:keyof GoalDraft,value:string|string[])=>setDraft(d=>({...d,[key]:value}));const toggle=(key:'groups'|'links'|'actions',value:string)=>change(key,draft[key].includes(value)?draft[key].filter(v=>v!==value):[...draft[key],value]);
 const coach=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/jarvis/goal-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const data=await r.json();if(!data.ok)throw Error(data.error);setQuestions(data.questions);}catch(e){setError(e instanceof Error?e.message:'KI nicht erreichbar');}finally{setBusy(false);}};
 const withDialogue=()=>({...draft,dialogue:[draft.dialogue,questions?'KI-Rückfragen (Vorschlag, keine Fakten):\n'+questions:'',reply?'Meine Antwort:\n'+reply:''].filter(Boolean).join('\n\n')});
 const save=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/vault/goals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(withDialogue())});const data=await r.json();if(!data.ok)throw Error(data.error);setStep(4);await refresh();choose(data.path);if(data.warnings?.length){setError(data.warnings.join(' '));setStep(4);}else onClose();}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen');}finally{setBusy(false);}};
 return <PanelWindow title="Neues Ziel · gemeinsam klären" slot="goal" onClose={onClose}><aside className="goal-panel goal-composer" aria-label="Neues Ziel"><p>Ein Ziel, eine Quelle: Nach deiner Bestätigung liegt alles direkt in Obsidian.</p><p className="goal-kicker">{['1 · Richtung','2 · Konkret werden','3 · Verbinden','4 · Prüfen und speichern','Gespeichert'][step]}</p>
 {step===0&&<><label>Was möchtest du erreichen?<input value={draft.title} maxLength={160} onChange={e=>change('title',e.target.value)} placeholder="Beschreibe einen gewünschten Zustand"/></label><label>Warum ist dir das wichtig?<textarea value={draft.why} maxLength={2000} onChange={e=>change('why',e.target.value)}/></label><fieldset><legend>Welche Lebensbereiche berührt es? Mehrere sind möglich.</legend>{DIRECTIONS.map(d=><label key={d.id}><input type="checkbox" checked={draft.groups.includes(d.id)} onChange={()=>toggle('groups',d.id)}/>{d.label}</label>)}</fieldset></>}
 {step===1&&<><label>Woran erkennst du, dass es erreicht ist?<textarea value={draft.measure} maxLength={2000} onChange={e=>change('measure',e.target.value)} placeholder="Darf bewusst offen bleiben"/></label><label>Welchen Zeithorizont hast du?<input value={draft.due} maxLength={10} onChange={e=>change('due',e.target.value)} placeholder="2027, 2027-06, 2027-06-15 oder offen lassen"/></label><label>Wie bedeutsam ist es für dich?<select value={draft.importance} onChange={e=>change('importance',e.target.value)}><option value="">Noch offen</option><option value="klein">Klein</option><option value="mittel">Mittel</option><option value="gross">Groß</option></select></label><label>Was wäre ein erster konkreter Meilenstein?<textarea value={draft.firstStep} maxLength={2000} onChange={e=>change('firstStep',e.target.value)}/></label></>}
 {step===2&&<><fieldset><legend>Welche vorhandenen Ziele oder Projekte stehen wirklich damit in Verbindung?</legend>{objects.filter(o=>o.kind!=='idea').map(o=><label key={o.id}><input type="checkbox" checked={draft.links.includes(o.path)} onChange={()=>toggle('links',o.path)}/>{o.title}</label>)}</fieldset><fieldset><legend>Welche deiner erfassten Handlungen unterstützen dieses Ziel?</legend>{HORIZON_ROUTINES.map(r=><label key={r.name}><input type="checkbox" checked={draft.actions.includes(r.name)} onChange={()=>toggle('actions',r.name)}/>{r.name}</label>)}</fieldset><button className="goal-source" disabled={busy||draft.title.trim().length<3} onClick={coach}>{busy?'Hermes denkt …':'Hermes: gezielte Rückfragen stellen'}</button><small>Sendet nur diesen Zielentwurf an deine bestehende Hermes-KI. Ohne Verbindung bleiben die geführten Fragen verfügbar.</small>{questions&&<><p className="goal-coach-questions">{questions}</p><label>Deine Antworten<textarea value={reply} maxLength={2000} onChange={e=>setReply(e.target.value)}/></label></>}</>}
 {step===3&&<><h3>{draft.title}</h3><p>Prüfe deinen Entwurf. Offene Angaben bleiben offen. Bestehende Notizen werden nicht überschrieben.</p><pre className="goal-draft-preview">{goalMarkdown(withDialogue(),'Datum beim Speichern')}</pre><button className="goal-source" disabled={busy} onClick={save}>{busy?'Wird in Obsidian gespeichert …':'Ziel bestätigen und in Obsidian speichern'}</button></>}
 {error&&<p role="status">{error}</p>}{step<4&&<div className="goal-step-travel"><button disabled={step===0||busy} onClick={()=>setStep(s=>s-1)}>Zurück</button>{step<3&&<button disabled={busy||draft.title.trim().length<3} onClick={()=>setStep(s=>s+1)}>Weiter</button>}</div>}
 </aside></PanelWindow>;
}
