"use client";
import {useEffect,useState} from 'react';
import {PROJECT_PHASES} from './projectMotion';
import {useWorlds} from './WorldsProvider';
const phaseTitle=(id:string)=>PROJECT_PHASES.find(p=>p.id===id)?.title??id;
export function ProjectCreate({phase}:{phase:string}){
 const {refresh,choose}=useWorlds();const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[goal,setGoal]=useState(''),[next,setNext]=useState(''),[folder,setFolder]=useState(''),[folders,setFolders]=useState<string[]>([]),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{if(!open)return;const abort=new AbortController();fetch('/api/vault/project-notes',{signal:abort.signal}).then(r=>r.json()).then(d=>{if(!d.ok)throw Error(d.error);setFolders(d.folders);}).catch(e=>{if(!abort.signal.aborted)setMessage(e.message);});return()=>abort.abort();},[open]);
 async function save(){if(busy||saved)return;setBusy(true);setMessage('');try{const res=await fetch('/api/vault/project-notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',title,goal,next,folder,phase})});const data=await res.json();if(!data.ok)throw Error(data.error);setSaved(true);setMessage('Projekt in Obsidian gespeichert. '+(data.warnings||[]).join(' '));try{await refresh();choose(data.path);}catch{setMessage('Projekt gespeichert. Raum bitte neu laden, um den neuen Planeten zu sehen.');}}catch(e){setMessage(e instanceof Error?e.message:'Speichern fehlgeschlagen');}finally{setBusy(false);}}
 return <section className="project-edit"><button className="worlds-primary" onClick={()=>setOpen(!open)} aria-expanded={open}>＋ Projekt in „{phaseTitle(phase)}“ anlegen</button>{open&&<><h3>Neues Projekt · {phaseTitle(phase)}</h3><fieldset disabled={busy||saved}>{!preview?<><label>Projektname<input value={title} maxLength={140} onChange={e=>setTitle(e.target.value)} placeholder="Ein konkretes Vorhaben"/></label><label>Projektbereich<select value={folder} onChange={e=>setFolder(e.target.value)}><option value="">Bereich auswählen</option>{folders.map(f=><option key={f} value={f}>{f.split('/').pop()}</option>)}</select></label><label>Was soll erreicht werden?<textarea value={goal} maxLength={4000} onChange={e=>setGoal(e.target.value)} placeholder="Darf bei einer frischen Idee noch offen bleiben"/></label><label>Was ist der nächste Schritt?<textarea value={next} maxLength={2000} onChange={e=>setNext(e.target.value)}/></label><button disabled={title.trim().length<3||!folder} onClick={()=>setPreview(true)}>Entwurf prüfen</button></>:<><h3>{title}</h3><p>Phase: {phaseTitle(phase)}</p><p>Ablage: {folder}</p><p>Ziel: {goal||'Noch offen'}</p><p>Nächster Schritt: {next||'Noch offen'}</p><small>Legt eine neue Projektnotiz an. Gleichnamige vorhandene Dateien werden nicht überschrieben.</small><button onClick={()=>setPreview(false)}>Zurück zum Entwurf</button><button className="worlds-primary" onClick={()=>void save()}>Projekt bestätigen und in Obsidian speichern</button></>}</fieldset>{message&&<p role="status">{message}</p>}{saved&&<button onClick={()=>{setSaved(false);setPreview(false);setTitle('');setGoal('');setNext('');setMessage('');}}>Weiteres Projekt anlegen</button>}</>}</section>;
}
export function ProjectPhaseEditor({id}:{id:string}){
 const {refresh}=useWorlds();const [open,setOpen]=useState(false),[current,setCurrent]=useState(''),[revision,setRevision]=useState(''),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setBusy(true);setMessage('');setRevision('');try{const res=await fetch('/api/vault/project-notes?id='+encodeURIComponent(id));const d=await res.json();if(!d.ok)throw Error(d.error);setCurrent(d.phase);setTarget(d.phase);setRevision(d.revision);}catch(e){setMessage(e instanceof Error?e.message:'Lesen fehlgeschlagen');}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{const res=await fetch('/api/vault/project-notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'phase',path:id,revision,phase:target,reason})});const d=await res.json();if(!d.ok)throw Error(d.error);setCurrent(target);setRevision(d.revision);setReason('');setMessage('Phase gespeichert. '+(d.warnings||[]).join(' '));try{await refresh();}catch{setMessage('Phase gespeichert. Raum bitte neu laden.');}}catch(e){setMessage(e instanceof Error?e.message:'Speichern fehlgeschlagen');}finally{setBusy(false);}}
 return <section className="project-edit"><button onClick={()=>{if(!open)void load();setOpen(!open);}} aria-expanded={open}>Projektphase bearbeiten</button>{open&&<><p>Dokumentierte Phase: {phaseTitle(current)||'Wird geladen …'}</p><fieldset disabled={busy||!revision||current==='abgeschlossen'}><label>Neue Projektphase<select value={target} onChange={e=>setTarget(e.target.value)}>{PROJECT_PHASES.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Was begründet den Wechsel?<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="Zum Beispiel: Entwurf steht, Umsetzung beginnt."/></label><small>Ändert die Phase in der Originalnotiz und ergänzt deine Begründung im Verlauf. „Fertig“ ist noch kein endgültiger Abschluss.</small><button className="worlds-primary" disabled={target===current||!reason.trim()} onClick={()=>void save()}>Phase {phaseTitle(current)} → {phaseTitle(target)} bestätigen</button></fieldset><button disabled={busy} onClick={()=>void load()}>Aktuellen Stand neu laden</button>{message&&<p role="status">{message}</p>}</>}</section>;
}
