"use client";
import {Billboard,Text,useGLTF} from '@react-three/drei';
import {useFrame} from '@react-three/fiber';
import {useMemo,useRef} from 'react';
import * as THREE from 'three';
import {useV2} from '../state';
import {COMMAND_STATES,useCommandPresence,openCommandArea} from './commandPresence';
const vertex=`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vec4 p=modelViewMatrix*vec4(position,1.);vP=p.xyz;gl_Position=projectionMatrix*p;}`;
const fragment=`uniform float time;uniform vec3 tint;uniform float strength;varying vec3 vN;varying vec3 vP;void main(){vec3 n=normalize(vN);float rim=pow(1.-max(0.,dot(n,normalize(-vP))),2.4);float bands=pow(.5+.5*sin(n.y*30.+n.x*9.+sin(n.z*12.+time)*2.-time*1.5),9.);float field=.5+.5*sin(n.x*9.+sin(n.y*8.-time*.5)+n.z*7.);vec3 col=vec3(.012,.028,.045)+tint*(rim*.85+bands*.32+field*.055)*strength;gl_FragColor=vec4(col,1.);}`;
export function CommandPlatform(){const {scene}=useGLTF('/models/hermes-command-r37.glb');return <primitive object={scene} dispose={null}/>;}
export function CommandCore({reachable,waiting,intensity}:{reachable:boolean;waiting:number;intensity:number}){
 const state=useCommandPresence(reachable,waiting);const {prefs}=useV2();const spec=COMMAND_STATES[state];const rings=useRef<THREE.Group>(null);const material=useRef<THREE.ShaderMaterial>(null);const uniforms=useMemo(()=>({time:{value:0},tint:{value:new THREE.Color(spec.color)},strength:{value:intensity}}),[spec.color,intensity]);
 useFrame((_,dt)=>{if(prefs.reducedMotion)return;const speed=state==='working'?1.8:state==='listening'?1.2:state==='speaking'?1.5:.28;if(material.current)material.current.uniforms.time.value+=Math.min(dt,.05)*speed;if(rings.current)rings.current.rotation.y+=Math.min(dt,.05)*speed*.16;});
 return <group position={[0,1.55,0]}><group onClick={e=>{e.stopPropagation();window.dispatchEvent(new Event('hermes:console-open'));}}><mesh><sphereGeometry args={[.76,48,32]}/><shaderMaterial ref={material} vertexShader={vertex} fragmentShader={fragment} uniforms={uniforms}/></mesh><group ref={rings}>{[0,1,2].map(i=><group key={i} rotation={[.6+i*.55,.4*i,.3+i*.55]}><mesh><torusGeometry args={[1.08+i*.13,.015,6,100,Math.PI*1.6]}/><meshStandardMaterial color={i===1?'#d7bc8d':spec.color} emissive={spec.color} emissiveIntensity={i===1?.08:.3} metalness={.8} roughness={.25}/></mesh><mesh position={[1.08+i*.13,0,0]}><sphereGeometry args={[.055,10,8]}/><meshBasicMaterial color={spec.color}/></mesh></group>)}</group></group><pointLight color={spec.color} intensity={4*intensity} distance={6}/><Billboard position={[0,1.8,0]}><Text fontSize={.25} color="#d8e8ee" letterSpacing={.2}>HERMES</Text><Text position={[0,-.38,0]} fontSize={.15} color={spec.color}>{spec.label}</Text></Billboard></group>;
}
export function CommandStations({projects,waiting,reachable}:{projects:number;waiting:number;reachable:boolean}){return <>{(['projects','tasks','decisions'] as const).map((area,i)=>{const p:[number,number,number]=[(i-1)*2.3,.72,i===1?4.15:3.55];return <group key={area} position={p}><mesh onClick={e=>{e.stopPropagation();openCommandArea(area);}}><boxGeometry args={[1.65,.3,.9]}/><meshBasicMaterial transparent opacity={0} depthWrite={false}/></mesh><Billboard position={[0,.25,0]}><Text fontSize={.19} color={i===2&&waiting?'#e5bc7a':'#bdcfda'} onClick={e=>{e.stopPropagation();openCommandArea(area);}}>{['PROJEKTE','AUFGABEN','FREIGABEN'][i]}</Text><Text position={[0,-.28,0]} fontSize={.13} color="#8faabb">{i===0?`${projects} offen`:i===1?'Todoist öffnen':reachable?`${waiting} warten`:'Status unbekannt'}</Text></Billboard></group>;})}</>;}
