"use client";
import {useEffect,useRef,useState} from 'react';import dynamic from 'next/dynamic';import Link from 'next/link';import {V2Provider} from '../v2/state';import {initialCouncil,demoSequence,reduceCouncil,actionPayload,approveTest,executeTest,ROLES,type CouncilState,type CouncilEvent} from './model';import {useCouncilVoice} from './useCouncilVoice';import './council.css';
const Scene=dynamic(()=>import('./CouncilScene'),{ssr:false});
const phases:Record<string,string>={briefing:'Frage klären',retrieving:'Quelle ansehen',positioning:'Vorschlag',debating:'Einwand prüfen',decision:'Deine Entscheidung',paused:'Unterbrochen',completed:'Test abgeschlossen'};
type LiveOpinion={id:'hermes'|'gemini';name:string;provider:string;ok:boolean;text:string|null;reason?:string};
function liveSequence(s:CouncilState,opinions:LiveOpinion[]):CouncilEvent[]{
 const events:CouncilEvent[]=[];
 const add=(event:Omit<CouncilEvent,'id'|'seq'|'sessionId'|'revision'>)=>{const seq=events.length+1;const complete={...event,id:s.id+':'+seq,seq,sessionId:s.id,revision:s.revision};events.push(complete);return complete;};
 add({type:'phase',text:'retrieving'});
 add({type:'claim',participant:'sources',source:'brief',text:s.source?'Geprüfte Grundlage ist ausschließlich das von dir freigegebene Briefing.':'Es wurde kein zusätzlicher Kontext freigegeben; beide Perspektiven kennen nur die Frage.'});
 add({type:'phase',text:'positioning'});
 const hermes=opinions.find(opinion=>opinion.id==='hermes');
 const gemini=opinions.find(opinion=>opinion.id==='gemini');
 const hermesClaim=hermes?.ok&&hermes.text?add({type:'claim',participant:'design',text:hermes.text}):null;
 add({type:'phase',text:'debating'});
 if(gemini?.ok&&gemini.text)add(hermesClaim?{type:'challenge',participant:'review',target:hermesClaim.id,text:gemini.text}:{type:'claim',participant:'review',text:gemini.text});
 const failures=opinions.filter(opinion=>!opinion.ok).map(opinion=>`${opinion.name}: ${opinion.reason||'nicht erreichbar'}`);
 add({type:'synthesis',participant:'moderator',text:[hermes?.ok&&gemini?.ok?'Zwei unabhängige Perspektiven liegen vor. Es wurde kein Konsens erzwungen.':'Eine Perspektive liegt vor; das ist noch keine vollständige Gegenprüfung.',failures.length?'Nicht erreichbar: '+failures.join(' · '):'', 'Du entscheidest, welche Annahme als Nächstes mit einem kleinen überprüfbaren Versuch getestet wird.'].filter(Boolean).join(' ')});
 return events;
}
export default function CouncilLab(){return <V2Provider><Council/></V2Provider>;}
function Council(){
 const [mission,setMission]=useState('Wie prüfen wir eine Idee mit einem kleinen Versuch?'),[source,setSource]=useState('Für den Versuch sind Erfolgskriterium und Aufwand noch offen.');const [state,setState]=useState<CouncilState>(()=>initialCouncil('preview','','')),[running,setRunning]=useState(false),[liveBusy,setLiveBusy]=useState(false),[panel,setPanel]=useState(true),[sourceOpen,setSourceOpen]=useState(false),[participant,setParticipant]=useState<string|null>(null),[view,setView]=useState('working'),[quiet,setQuiet]=useState(false),[voiceText,setVoiceText]=useState(''),[audio,setAudio]=useState(false),[notice,setNotice]=useState(''),[speaking,setSpeaking]=useState(false);
 const archive=useRef<CouncilEvent[]>([]);const [queue,setQueue]=useState<CouncilEvent[]>([]);const active=state.events.at(-1);
 const pause=()=>{setSpeaking(false);setRunning(false);setState(s=>({...s,phase:'paused'}));window.speechSynthesis?.cancel();};const voice=useCouncilVoice(setVoiceText,pause);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setQuiet(media.matches);const frame=requestAnimationFrame(update);media.addEventListener('change',update);return()=>{cancelAnimationFrame(frame);media.removeEventListener('change',update);};},[]);
 useEffect(()=>{if(!running||speaking)return;const next=queue[state.events.length];if(!next)return;const timer=setTimeout(()=>{setState(s=>reduceCouncil(s,next));},quiet||view==='compact'?650:view==='cinematic'?3200:2100);return()=>clearTimeout(timer);},[running,queue,state.events.length,quiet,view,speaking]);
 useEffect(()=>{if(state.mode!=='replay')archive.current=state.events;},[state.events,state.mode]);
 useEffect(()=>{if(!audio||voice.listening||!running||!active?.participant||!['claim','challenge','synthesis'].includes(active.type))return;window.speechSynthesis?.cancel();const speech=new SpeechSynthesisUtterance(active.text);speech.lang='de-DE';speech.rate=1.02;speech.onstart=()=>setSpeaking(true);speech.onend=()=>setSpeaking(false);speech.onerror=()=>{setSpeaking(false);setNotice('Vorlesen nicht verfügbar; der vollständige Text bleibt erhalten.');};window.speechSynthesis?.speak(speech);return()=>{window.speechSynthesis?.cancel();};},[active,audio,voice.listening,running]);
 function start(){setSpeaking(false);voice.stop();window.speechSynthesis?.cancel();const s=initialCouncil(crypto.randomUUID(),mission.trim(),source,state.revision+1);setState(s);setQueue(demoSequence(s));setRunning(true);setNotice('DEMO · Keine Modelle, keine privaten Quellen, keine produktiven Schreibaktionen.');}
 async function startLive(){
  if(!mission.trim()||liveBusy)return;
  pause();setLiveBusy(true);setNotice('Hermes und Gemini prüfen das Briefing unabhängig voneinander …');
  const s=initialCouncil(crypto.randomUUID(),mission.trim(),source,state.revision+1,'live');setState(s);setQueue([]);
  try{
   const response=await fetch('/api/council/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mission:mission.trim(),context:source})});
   const data=await response.json();
   if(!data.ok)throw new Error(data.reason||'Live-Konsil nicht erreichbar.');
   const next=liveSequence(s,data.opinions as LiveOpinion[]);setQueue(next);setRunning(true);setNotice('LIVE · Hermes und Gemini antworten getrennt. Keine Datei, Aufgabe oder Nachricht wird geschrieben.');
  }catch(error){setState(current=>({...current,phase:'paused'}));setNotice(error instanceof Error?error.message:String(error));}
  finally{setLiveBusy(false);}
 }
 function revise(){pause();const s=initialCouncil(crypto.randomUUID(),mission,source,state.revision+1);setState(s);setQueue([]);setNotice('Neues Briefing. Vorherige Beiträge und Freigaben gelten nicht für diese Revision.');}
 function replay(){setSpeaking(false);voice.stop();window.speechSynthesis?.cancel();const saved=archive.current;if(!saved.length)return;setState({...state,mode:'replay',events:[],phase:'briefing',approval:null,applied:0,testTask:undefined});setQueue(saved);setRunning(true);setNotice('REPLAY · Nur gespeicherte Ereignisse; alle Aktionen gesperrt.');}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({...state,schemaVersion:1},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Hermes-Konsil-Testprotokoll.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const proposal=actionPayload(state),role=ROLES.find(r=>r.id===participant);const lastContribution=[...state.events].reverse().find(e=>['claim','challenge','synthesis'].includes(e.type));
 return <main className={'council-lab '+view}><div className="council-space"><Scene state={state} quiet={quiet} onSource={()=>setSourceOpen(true)} onParticipant={setParticipant}/></div>
 <header className="council-top"><div><span>HERMES · KONSIL / {state.mode.toUpperCase()}</span><h1>Gemeinsam klarer sehen.</h1><p>{phases[state.phase]} · Briefing {state.revision}</p></div><Link href="/v2">← Zuhause</Link></header>
 <nav className="council-controls" aria-label="Konsil steuern"><button onClick={()=>setPanel(!panel)}>{panel?'Pult minimieren':'Pult öffnen'}</button><select aria-label="Darstellung" value={view} onChange={e=>setView(e.target.value)}><option value="compact">Kompakt</option><option value="working">Arbeitsmodus</option><option value="cinematic">Cinematic</option></select><button onClick={pause}>Unterbrechen</button><button onClick={()=>{setSpeaking(false);setAudio(!audio);window.speechSynthesis?.cancel();}}>{audio?'Vorlesen aus':'Vorlesen an'}</button><button onClick={()=>setQuiet(!quiet)}>{quiet?'Bewegung ruhig':'Bewegung an'}</button></nav>
 {lastContribution&&<aside className="council-contribution"><span>{ROLES.find(r=>r.id===lastContribution.participant)?.name} · {lastContribution.type==='challenge'?'OFFENER EINWAND':'SICHTBARER BEITRAG'}</span><p>{lastContribution.text}</p>{lastContribution.target&&<button onClick={()=>{setPanel(true);setNotice('Bezug: '+state.events.find(e=>e.id===lastContribution.target)?.text);}}>Angegriffene Aussage zeigen</button>}</aside>}
 {panel&&<aside className="council-pult" aria-label="Konsil Arbeitsfläche"><div className="council-panel-head"><strong>Briefing & Entscheidung</strong><button aria-label="Pult schließen" onClick={()=>setPanel(false)}>×</button></div><p className="council-note">Live-Konsil: Hermes entwickelt die Hauptsicht, Gemini prüft unabhängig über deinen angemeldeten Google-AI-Pro-Zugang. Beide erhalten nur Frage und freigegebenen Kontext.</p>
 <label>Deine Frage<textarea value={mission} maxLength={2000} onChange={e=>{setMission(e.target.value);pause();}}/></label><label>Freigegebener Testkontext<textarea value={source} maxLength={6000} onChange={e=>{setSource(e.target.value);pause();}}/></label><button disabled={!mission.trim()||(running&&state.events.length<queue.length)} onClick={start}>Demo mit diesem Briefing starten</button>{state.phase==='paused'&&<button onClick={revise}>Geändertes Briefing übernehmen</button>}
 <button disabled={!mission.trim()||liveBusy||(running&&state.events.length<queue.length)} onClick={()=>void startLive()}>{liveBusy?'Perspektiven werden eingeholt …':'Live-Konsil starten · Hermes + Gemini'}</button>
 <details><summary>Spracheingabe</summary><p>Optional: Dein Browser kann Audio an seinen Erkennungsdienst übertragen. Keine Audioarchivierung durch Hermes. Diktat unterbricht die Sitzung; du prüfst den Text vor der Übernahme.</p><button onClick={voice.listening?voice.stop:voice.start}>{voice.listening?'Mikrofon stoppen':'Mikrofon bewusst aktivieren'}</button><p role="status">{voice.status}</p><textarea aria-label="Diktierter Entwurf" value={voiceText} onChange={e=>setVoiceText(e.target.value)}/><button disabled={!voiceText.trim()} onClick={()=>{voice.stop();setMission(voiceText);revise();setNotice('Diktat in der Frage. Starte die Demo erst nach deiner Prüfung erneut.');}}>Als Frage übernehmen</button></details>
 {state.phase==='decision'||state.phase==='completed'?<section><h2>Entscheidungspult</h2><p>{state.events.find(e=>e.type==='synthesis')?.text}</p><p>{state.mode==='live'?'Perspektiven bleiben getrennt · keine automatische Abstimmung':'1 Vorschlag · 1 offener Einwand · keine Abstimmung erfolgt'}</p>{state.mode==='live'?<p>Wähle selbst, was weiterverfolgt wird. Das Live-Konsil besitzt in dieser Stufe keinen Schreibzugriff.</p>:<><button disabled={state.mode==='replay'} onClick={()=>setNotice('Empfehlung vorgemerkt. Es wurde keine Aufgabe oder Datei angelegt.')}>Empfehlung vormerken</button><details><summary>Exakte Testaktion ansehen</summary><pre>{proposal}</pre><p>Nur eine Aufgabe im flüchtigen Testspeicher dieser Sitzung. Kein Obsidian- oder Todoist-Schreibzugriff.</p><button disabled={state.mode==='replay'||!!state.applied} onClick={()=>setState(s=>executeTest(approveTest(s,proposal)))}>Diese Testaktion freigeben & ausführen</button><p>{state.applied?'✓ Eine Testaufgabe ausgeführt.':'Noch nicht ausgeführt.'}</p></details></>}</section>:null}
 <details><summary>Protokoll · {state.events.length} Ereignisse</summary>{state.events.map(e=><article key={e.id}><small>{e.seq} · {e.type}</small><p>{e.text}</p></article>)}</details><button disabled={!state.events.length||(running&&state.events.length<queue.length)} onClick={replay}>Verlauf als Replay ansehen</button><button disabled={!state.events.length} onClick={download}>Testprotokoll herunterladen</button><p role="status">{notice}</p></aside>}
 {sourceOpen&&<aside className="council-source"><button aria-label="Quelle schließen" onClick={()=>setSourceOpen(false)}>×</button><h2>Quelle 01 · Freigegebenes Briefing</h2><p>Fundstelle: eingegebener Kontext, Briefing {state.revision}. Kein externer Abruf.</p><blockquote>{state.source||'Keine Quelle eingegeben.'}</blockquote></aside>}{role&&<aside className="council-source"><button onClick={()=>setParticipant(null)}>×</button><h2>{role.name}</h2><p>{role.role}</p><p>{state.mode==='live'?(role.id==='review'?'Provider: Google AI Pro · Antigravity CLI':role.id==='design'?'Provider: Hermes Gateway':'Rolle im Konsil'):'Modell: keines · Provider: keiner · DEMO'}</p></aside>}
 </main>;
}
