"use client";
import {cloneElement,useState,useEffect,type ReactElement,type ReactNode,type CSSProperties} from 'react';
/** Keep the body mounted so minimizing preserves text, scroll position and drafts. */
export function PanelWindow({title,children,slot='left',onClose,onMinimizedChange}:{title:string;children:ReactElement<{children?:ReactNode;style?:CSSProperties}>;slot?:string;onClose?:()=>void;onMinimizedChange?:(minimized:boolean)=>void}){
 const [mode,setMode]=useState<'open'|'minimized'|'closed'>('open');
 useEffect(()=>{const show=(event:Event)=>{if((event as CustomEvent).detail===slot){setMode('open');onMinimizedChange?.(false);}};window.addEventListener('hermes:panel-open',show);return()=>window.removeEventListener('hermes:panel-open',show);},[slot,onMinimizedChange]);
 useEffect(()=>{const minimize=()=>{if(mode!=='open')return;setMode('minimized');onMinimizedChange?.(true);};const restore=()=>{if(mode!=='minimized')return;setMode('open');onMinimizedChange?.(false);};window.addEventListener('hermes:panels-minimize',minimize);window.addEventListener('hermes:panels-restore',restore);return()=>{window.removeEventListener('hermes:panels-minimize',minimize);window.removeEventListener('hermes:panels-restore',restore);};},[mode,onMinimizedChange]);
 const close=()=>{if(onClose)onClose();else setMode('closed');};
 return <>{mode!=='open'&&<div className={`panel-restore panel-slot-${slot}`}><button onClick={()=>{setMode('open');onMinimizedChange?.(false);}} aria-label={`${title} wiederherstellen`}>↗ {title}{mode==='closed'?' öffnen':''}</button>{mode==='minimized'&&<button aria-label={`${title} schließen`} onClick={close}>×</button>}</div>}{cloneElement(children,{style:{...children.props.style,...(mode==='open'?{}:{display:'none'})}},<><div className="panel-window-tools" onClick={event=>event.stopPropagation()}><span>{title}</span><button aria-label={`${title} minimieren`} onClick={()=>{setMode('minimized');onMinimizedChange?.(true);}}>—</button><button aria-label={`${title} schließen`} onClick={close}>×</button></div>{children.props.children}</>)}</>;
}
