"use client";
import Link from 'next/link';
import {COMMAND_STATES,useCommandPresence} from '../world/commandPresence';
import {useEffect,useState} from 'react';
import {useWorlds} from '../foundations/WorldsProvider';
import {useV2} from '../state';
import {PanelWindow} from './PanelWindow';
import {approvalTitle,type PendingApproval} from './Approvals';
import {localDay,orderedTasks,taskDate,type WorkTask} from './workCentralModel';
import './workCentral.css';
export function WorkCentral({onRead,onApprovals,approvals,reachable}:{onRead:(path:string)=>void;onApprovals:()=>void;approvals:PendingApproval[];reachable:boolean}){
 const {objects,loading,issues,refresh,choose}=useWorlds();const {goTo}=useV2();
 const presence=useCommandPresence(reachable,approvals.length),signal=COMMAND_STATES[presence];
 const [tab,setTab]=useState<'projects'|'tasks'|'decisions'>('projects');
 useEffect(()=>{const show=(event:Event)=>{const value=(event as CustomEvent).detail;if(value==='tasks'||value==='projects'||value==='decisions'){sessionStorage.removeItem('hermes:work-tab');setTab(value);window.dispatchEvent(new CustomEvent('hermes:panel-open',{detail:'work'}));}};window.addEventListener('hermes:work-tab',show);const pending=sessionStorage.getItem('hermes:work-tab');if(pending){sessionStorage.removeItem('hermes:work-tab');show(new CustomEvent('hermes:work-tab',{detail:pending}));}return()=>window.removeEventListener('hermes:work-tab',show);},[]);
 const [tasks,setTasks]=useState<WorkTask[]>([]);const [status,setStatus]=useState('Noch nicht abgerufen');const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);const [stamp,setStamp]=useState('');const [filter,setFilter]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{if(tab!=='tasks')return;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);let active=true;
 async function read(){setBusy(true);setStatus('Todoist wird abgerufen …');setTasks([]);setStamp('');try{const token=localStorage.getItem('hermes_todoist_token');const response=await fetch('/api/todoist/tasks',{signal:controller.signal,cache:'no-store',headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok)throw Error('Todoist derzeit nicht erreichbar');const data=await response.json();if(!active)return;if(!data.connected||!Array.isArray(data.tasks)){setStatus('Todoist nicht verbunden. Die bestehende Todoist-Anbindung prüfen.');return;}setTasks(data.tasks);setStatus('Todoist · aktuelle Aufgaben');setStamp(new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}));}catch{if(active)setStatus('Abruf fehlgeschlagen oder Zeitlimit erreicht. Erneut versuchen.');}finally{clearTimeout(timeout);if(active)setBusy(false);}}
 void read();return()=>{active=false;clearTimeout(timeout);controller.abort();};},[tab,reload]);
 const projects=objects.filter(o=>o.kind==='project'&&!['fertig','abgeschlossen'].includes(o.state)&&o.title.toLocaleLowerCase('de').includes(filter.toLocaleLowerCase('de')));
 const today=localDay(new Date());const ordered=orderedTasks(tasks,today);
 const draft=(title:string,context:string)=>{window.dispatchEvent(new CustomEvent('hermes:jarvis-draft',{detail:`Hilf mir bei: ${title}\n\nDokumentierter Kontext:\n${context}\n\nPrüfe den nächsten sinnvollen Schritt. Trenne belegte Angaben von Vorschlägen und frage bei fehlenden Informationen nach.`}));};
 return <PanelWindow title="Arbeitszentrale" slot="work"><aside className="work-central" aria-label="Arbeitszentrale"><div className="work-intro"><span>DEINE KOMMANDOZENTRALE</span><h2>Was steht als Nächstes an?</h2><div className="command-presence" role="status"><i style={{background:signal.color}}/><strong>Jarvis // Hermes · {signal.label}</strong></div><p>{signal.detail}</p><div className="command-shortcuts"><button onClick={()=>window.dispatchEvent(new Event('hermes:console-open'))}>Jarvis // Hermes öffnen ↗</button><button onClick={()=>window.dispatchEvent(new Event('hermes:deck-focus'))}>Deck ansehen</button></div></div><nav aria-label="Arbeitszentrale Bereiche">{(['projects','tasks','decisions'] as const).map((t,i)=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{['Projekte','Aufgaben','Entscheidungen'][i]}{t==='decisions'&&reachable?` · ${approvals.length}`:''}</button>)}</nav><div className="work-content">
 {tab==='projects'&&<><div className="work-source"><span>Obsidian · {loading?'lädt …':`${projects.length} offene Projekte`}</span><button onClick={()=>{setNotice('');void refresh().catch(()=>setNotice('Projektstände konnten nicht aktualisiert werden. Angezeigte Daten sind der letzte geladene Stand.'));}}>Aktualisieren</button></div><p className="work-hint">Aus deinen Projektnotizen. Ältere Einträge können überholt sein; die Aktualität ist nicht automatisch geprüft.</p><input aria-label="Projekt in Arbeitszentrale suchen" placeholder="Projekt finden …" value={filter} onChange={e=>setFilter(e.target.value)}/>{notice&&<p role="status">{notice}</p>}{issues.length>0&&<p role="status">Projektquelle meldet Einschränkungen. Die Übersicht kann unvollständig sein.</p>}{!loading&&!projects.length&&<p>Keine passenden offenen Projekte in den geladenen Raumdaten.</p>}{projects.map(project=><article key={project.id}><small>{project.state}{project.waiting?` · Am Zug: ${project.waiting}`:''}</small><h3>{project.title}</h3>{project.workDate&&<small>Arbeitsstand vom {project.workDate}</small>}{project.current&&<details className="work-context"><summary>Stand & Kontext</summary><p>{project.current}</p></details>}<div className="work-next"><span>{project.nextTodo?`Aus der Notiz: ${project.nextHeading||'Nächster Schritt'}`:'Nächsten Schritt klären'}</span><p>{project.nextTodo||'In der Projektnotiz ist noch kein nächster Schritt erfasst.'}</p></div>{project.blocker&&<details><summary>Blocker / offene Prüfung</summary><p>{project.blocker}</p></details>}<div className="work-actions"><button onClick={()=>{choose(project.id);goTo('projects');}}>Zum Projekt →</button><button onClick={()=>onRead(project.path)}>Originalnotiz</button><button onClick={()=>draft(project.title,`${project.path}\n${project.current||''}\n${project.nextTodo||'Nächster Schritt fehlt.'}`)}>Mit Hermes klären</button></div></article>)}</>}
 {tab==='tasks'&&<><div className="work-source"><span>{status}{stamp?` · ${stamp}`:''}</span><button disabled={busy} onClick={()=>setReload(n=>n+1)}>Aktualisieren</button></div><p className="work-hint">Nach Fälligkeit, dann Priorität. Bearbeitung bleibt in Todoist.</p>{stamp&&ordered.length===0&&<p>Keine offenen Aufgaben gemeldet.</p>}{ordered.map(task=><article key={task.id}><small>{task.projectName||'Todoist'} · {taskDate(task.dueDate)?taskDate(task.dueDate)!<today?'Überfällig':taskDate(task.dueDate)===today?'Heute':taskDate(task.dueDate):'Ohne Termin'}</small><h3>{task.content}</h3><div className="work-actions"><a href={`https://app.todoist.com/app/task/${encodeURIComponent(task.id)}`} target="_blank" rel="noreferrer">In Todoist öffnen ↗</a><button onClick={()=>draft(task.content,`Todoist-Aufgabe ${task.id}, Termin: ${taskDate(task.dueDate)||'nicht festgelegt'}`)}>Mit Hermes klären</button></div></article>)}</>}
 {tab==='decisions'&&<><p className="work-source">Hermes · wartende Freigaben</p>{!reachable?<p>Hermes ist derzeit nicht erreichbar. Offene Entscheidungen sind nicht bekannt.</p>:approvals.length===0?<p>Hermes meldet derzeit keine wartenden Freigaben.</p>:approvals.map((a,i)=><article key={i}><h3>{approvalTitle(a)}</h3><button onClick={onApprovals}>Freigabe ansehen →</button></article>)}<p className="work-hint">Weitere offene Fragen stehen bei den Projekten. Hermes kann beim Abwägen helfen; eine unabhängige zweite KI ist hier noch nicht angebunden.</p><Link href="/council-lab">Konsil-Testbühne öffnen ↗</Link></>}
 </div><footer>„Mit Hermes klären“ bereitet eine Frage vor. Erst Absenden startet die bestehende KI-Anbindung.</footer></aside></PanelWindow>;
}
