import {createElement} from 'react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {FlowProvider,FlowWorkspace} from '@/features/v2/foundations/FlowWorkspace';
vi.mock('@/features/v2/foundations/WorldsProvider',()=>({useWorlds:()=>({selected:null,choose:vi.fn(),travel:vi.fn(),jobs:[],flowStatus:'Keine Verbindung'})}));
const flow={project:'05 🚀 Projekte/Content/Test.md',title:'Pilot',revision:'a'.repeat(64),history:[],stages:[{id:'text',title:'Skript',description:'Text prüfen',next:'Lesen',status:'offen',files:[]}]};
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
const view=()=>render(createElement(FlowProvider,{world:'flow',children:createElement(FlowWorkspace,{onRead:vi.fn()})}));
describe('bewusste Flow-Statusänderung',()=>{
 it('fordert die Übersicht auch bei wiederholtem Klick erneut an',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({flows:[flow],issues:[]})}));const overview=vi.fn();window.addEventListener('hermes:flow-overview',overview);try{view();const button=await screen.findByRole('button',{name:'Gesamten Ablauf ansehen ↗'});fireEvent.click(button);fireEvent.click(button);expect(overview).toHaveBeenCalledTimes(2);}finally{window.removeEventListener('hermes:flow-overview',overview);}});
 it('sendet erst nach begründeter Bestätigung und zeigt den gespeicherten Stand',async()=>{const fetcher=vi.fn().mockResolvedValueOnce({ok:true,json:async()=>({flows:[flow],issues:[]})}).mockResolvedValueOnce({ok:true,json:async()=>({flow:{...flow,revision:'b'.repeat(64),stages:[{...flow.stages[0],status:'fertig'}]}})});vi.stubGlobal('fetch',fetcher);view();await screen.findByRole('heading',{name:'Skript'});fireEvent.click(screen.getByText('Status festhalten'));const save=screen.getByRole('button',{name:'In Obsidian festhalten'});expect(save).toBeDisabled();fireEvent.change(screen.getByLabelText('Neuer Stand'),{target:{value:'fertig'}});expect(save).toBeDisabled();fireEvent.change(screen.getByLabelText('Was wurde geprüft oder was fehlt?'),{target:{value:'Text komplett geprüft.'}});expect(fetcher).toHaveBeenCalledTimes(1);fireEvent.click(save);await screen.findByText('1 von 1 Stationen bestätigt · keine automatische Ausführung');expect(JSON.parse(fetcher.mock.calls[1][1].body)).toMatchObject({status:'fertig',reason:'Text komplett geprüft.',revision:flow.revision});});
 it('erhält die Begründung bei einem Speicherkonflikt',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce({ok:true,json:async()=>({flows:[flow],issues:[]})}).mockResolvedValueOnce({ok:false,json:async()=>({error:'Die Projektnotiz wurde geändert. Bitte neu laden.'})}));view();await screen.findByRole('heading',{name:'Skript'});fireEvent.click(screen.getByText('Status festhalten'));fireEvent.change(screen.getByLabelText('Neuer Stand'),{target:{value:'fertig'}});fireEvent.change(screen.getByLabelText('Was wurde geprüft oder was fehlt?'),{target:{value:'Meine Begründung'}});fireEvent.click(screen.getByRole('button',{name:'In Obsidian festhalten'}));await screen.findByRole('alert');await waitFor(()=>expect(screen.getByLabelText('Was wurde geprüft oder was fehlt?')).toHaveValue('Meine Begründung'));});
});
