// @vitest-environment node
import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {listFlows,readFlow,updateFlow,flowFile,parseFlow} from '@/lib/flowNotes';
import {GET as mediaGET} from '@/app/api/vault/flows/file/route';
import {POST} from '@/app/api/vault/flows/route';
let root:string,vault:string,assets:string;
const id='05 🚀 Projekte/Content/Test.md';
beforeEach(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'hermes-flow-test-'));vault=path.join(root,'vault');assets=path.join(root,'media');await fs.mkdir(path.join(vault,'05 🚀 Projekte','Content'),{recursive:true});await fs.mkdir(assets);await fs.writeFile(path.join(assets,'script.txt'),'Originaltext');await fs.writeFile(path.join(vault,id),'---\nphase: in-arbeit\n---\nPersönliche Notiz bleibt unverändert.\n\n```hermes-flow\n'+JSON.stringify({version:1,title:'Pilot',root:assets,stages:[{id:'text',title:'Text',description:'Prüfen',next:'Lesen',status:'offen',files:[{id:'text',label:'Text',path:'script.txt'},{id:'missing',label:'Nicht da',path:'missing.mp4'}]}],history:[],extra:'preserve'})+'\n```\n\nNachfolgender Kontext.\n');});
afterEach(async()=>{await fs.rm(root,{recursive:true,force:true});});
describe('Flow aus der kanonischen Projektnotiz',()=>{
 it('trennt vorhandene Artefakte von bestätigten Stationen',async()=>{const d=await listFlows(vault);expect(d.flows).toHaveLength(1);expect(d.flows[0].stages[0].status).toBe('offen');expect(d.flows[0].stages[0].files.map(f=>f.exists)).toEqual([true,false]);expect(JSON.stringify(d)).not.toContain(assets.replaceAll('\\','\\\\'));});
 it('schreibt nur den Flow-Block, sichert vorher und protokolliert die Begründung',async()=>{const before=await fs.readFile(path.join(vault,id),'utf8');const d=await readFlow(vault,id);const r=await updateFlow(vault,{project:id,stage:'text',status:'fertig',reason:'Vollständig geprüft.',revision:d.revision});expect(r.flow.stages[0].status).toBe('fertig');expect(r.flow.history[0].reason).toBe('Vollständig geprüft.');const after=await fs.readFile(path.join(vault,id),'utf8');const a=parseFlow(before)!,b=parseFlow(after)!;expect(before.slice(0,a.start)).toBe(after.slice(0,b.start));expect(before.slice(a.start+a.length)).toBe(after.slice(b.start+b.length));expect(after).toContain('"extra": "preserve"');expect(await fs.readFile(path.join(path.dirname(path.join(vault,id)),'.hermes-history','Test.md.'+d.revision+'.md'),'utf8')).toBe(before);});
 it('überschreibt keine zwischenzeitliche Änderung',async()=>{const d=await readFlow(vault,id);await fs.appendFile(path.join(vault,id),'Extern ergänzt.');await expect(updateFlow(vault,{project:id,stage:'text',status:'fertig',reason:'Test',revision:d.revision})).rejects.toMatchObject({status:409});expect((await readFlow(vault,id)).stages[0].status).toBe('offen');});
 it('respektiert die gemeinsame Projektsperre',async()=>{const d=await readFlow(vault,id);await fs.writeFile(path.join(vault,id)+'.hermes-lock','');await expect(updateFlow(vault,{project:id,stage:'text',status:'fertig',reason:'Test',revision:d.revision})).rejects.toMatchObject({status:409});});
 it('liefert nur zugeordnete Medien und blockiert Pfadtraversal',async()=>{expect((await flowFile(vault,id,'text','text')).size).toBe(12);await expect(flowFile(vault,id,'text','anderes')).rejects.toThrow();await expect(flowFile(vault,'05 🚀 Projekte/../secret.md','text','text')).rejects.toThrow();const text=await fs.readFile(path.join(vault,id),'utf8');expect(()=>parseFlow(text.replace('script.txt','../secret.txt'))).toThrow();});
 it('verweigert mehrdeutige Blöcke und doppelte Stationskennungen',async()=>{const text=await fs.readFile(path.join(vault,id),'utf8');expect(()=>parseFlow(text+text)).toThrow();const d=parseFlow(text)!.manifest;d.stages.push(d.stages[0]);expect(()=>parseFlow('```hermes-flow\n'+JSON.stringify(d)+'\n```')).toThrow();});
 it('unterstützt begrenzte Medienbereiche und verweigert ungültige Bereiche',async()=>{const prev=process.env.OBSIDIAN_VAULT_PATH;process.env.OBSIDIAN_VAULT_PATH=vault;try{const url='http://localhost/api/vault/flows/file?'+new URLSearchParams({project:id,stage:'text',file:'text'});const r=await mediaGET(new Request(url,{headers:{range:'bytes=0-3'}}));expect(r.status).toBe(206);expect(r.headers.get('content-range')).toBe('bytes 0-3/12');expect(await r.text()).toBe('Orig');expect((await mediaGET(new Request(url,{headers:{range:'bytes=100-200'}}))).status).toBe(416);}finally{if(prev===undefined)delete process.env.OBSIDIAN_VAULT_PATH;else process.env.OBSIDIAN_VAULT_PATH=prev;}});
 it('verweigert fremde Schreibzugriffe vor der Verarbeitung',async()=>{const r=await POST(new Request('http://localhost/api/vault/flows',{method:'POST',headers:{host:'localhost',origin:'https://foreign.example'},body:'{}'}));expect(r.status).toBe(403);});
});
