import {describe,it,expect} from 'vitest';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createProject,changeProjectPhase,readProject,projectFolders} from '../../src/lib/projectNotes';
import {toObject} from '../../src/features/v2/foundations/model';
async function vault(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'hermes-project-edit-test-'));await fs.mkdir(path.join(root,'05 🚀 Projekte/06 Experimente'),{recursive:true});await fs.mkdir(path.join(root,'02⚙️ System'));await fs.writeFile(path.join(root,'Index.md'),'Index\n');await fs.writeFile(path.join(root,'02⚙️ System/Log.md'),'History\n');return root;}
const draft={title:'Testprojekt: ein Vorhaben',folder:'05 🚀 Projekte/06 Experimente',phase:'idee',goal:'Ein überprüfbares Ergebnis',next:'Den Entwurf schreiben'};
describe('canonical project workspace',()=>{
 it('creates a readable project with an explicit phase, title, and next step',async()=>{const root=await vault(),result=await createProject(root,draft),text=await fs.readFile(path.join(root,result.path),'utf8'),object=toObject(result.path,text)!;expect(object.kind).toBe('project');expect(object.title).toBe(draft.title);expect(object.state).toBe('idee');expect(object.nextTodo).toBe(draft.next);expect(await fs.readFile(path.join(root,'Index.md'),'utf8')).toContain(result.path.replace(/\.md$/,''));expect(await fs.readFile(path.join(root,'02⚙️ System/Log.md'),'utf8')).toMatch(/^History/);});
 it('never overwrites a same-name note',async()=>{const root=await vault(),r=await createProject(root,draft),before=await fs.readFile(path.join(root,r.path),'utf8');await expect(createProject(root,draft)).rejects.toThrow('gleichnamige');expect(await fs.readFile(path.join(root,r.path),'utf8')).toBe(before);});
 it('preserves unrelated metadata/body and a full backup while changing phase',async()=>{const root=await vault(),r=await createProject(root,draft),full=path.join(root,r.path);let before=(await fs.readFile(full,'utf8')).replace('phase: idee','custom: "unverändert"\nphase: idee')+'\n## Eigene Gedanken\nOriginal bleibt.\n';before=before.replace(/\n/g,'\r\n');await fs.writeFile(full,before);const read=await readProject(root,r.path);const result=await changeProjectPhase(root,{path:r.path,revision:read.revision,phase:'entwurf',reason:'Ziel und Umfang festgelegt'});const after=await fs.readFile(full,'utf8');expect(after).toContain('custom: "unverändert"');expect(after).toContain('## Eigene Gedanken\r\nOriginal bleibt.');expect(after).toContain('idee → entwurf');expect(toObject(r.path,after)!.state).toBe('entwurf');expect(result.revision).not.toBe(read.revision);const backups=await fs.readdir(path.join(path.dirname(full),'.hermes-history'));expect(await fs.readFile(path.join(path.dirname(full),'.hermes-history',backups[0]),'utf8')).toBe(before);});
 it('rejects a stale version without touching a newer edit',async()=>{const root=await vault(),r=await createProject(root,draft),full=path.join(root,r.path);await fs.appendFile(full,'\nNeue externe Änderung');const newer=await fs.readFile(full,'utf8');await expect(changeProjectPhase(root,{path:r.path,revision:r.revision,phase:'in-arbeit',reason:'Start'})).rejects.toThrow('inzwischen');expect(await fs.readFile(full,'utf8')).toBe(newer);});
 it('rejects traversal, invalid folders and automatic completion',async()=>{const root=await vault();await expect(createProject(root,{...draft,folder:'05 🚀 Projekte/../../01 RAW'})).rejects.toThrow();await expect(createProject(root,{...draft,phase:'abgeschlossen'})).rejects.toThrow();await expect(readProject(root,'05 🚀 Projekte/../Index.md')).rejects.toThrow();expect(await projectFolders(root)).toEqual([draft.folder]);});
 it('requires a reason and refuses ambiguous phase metadata',async()=>{const root=await vault(),r=await createProject(root,draft);await expect(changeProjectPhase(root,{path:r.path,revision:r.revision,phase:'entwurf',reason:''})).rejects.toThrow();const full=path.join(root,r.path);await fs.writeFile(full,(await fs.readFile(full,'utf8')).replace('phase: idee','phase: idee\nphase: entwurf'));const read=await readProject(root,r.path);await expect(changeProjectPhase(root,{path:r.path,revision:read.revision,phase:'fertig',reason:'Prüfung'})).rejects.toThrow('Mehrdeutige');});
 it('serializes competing writes and preserves the winning phase',async()=>{const root=await vault(),r=await createProject(root,draft);const results=await Promise.allSettled(['entwurf','in-arbeit'].map(phase=>changeProjectPhase(root,{path:r.path,revision:r.revision,phase,reason:'Teständerung'})));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);});
 it('does not reopen an archived completed project implicitly',async()=>{const root=await vault(),r=await createProject(root,draft),full=path.join(root,r.path);await fs.writeFile(full,(await fs.readFile(full,'utf8')).replace('phase: idee','phase: abgeschlossen'));const read=await readProject(root,r.path);await expect(changeProjectPhase(root,{path:r.path,revision:read.revision,phase:'entwurf',reason:'Noch etwas'})).rejects.toThrow('Abgeschlossene');});
});

import {POST} from '../../src/app/api/vault/project-notes/route';
describe('custom server origin validation',()=>{
 const request=(origin?:string,site?:string)=>new Request('http://127.0.0.1:3492/api/vault/project-notes',{method:'POST',headers:{host:'localhost:3492','content-type':'application/json',...(origin?{origin}:{}),...(site?{'sec-fetch-site':site}:{})},body:JSON.stringify({action:'invalid'})});
 it('accepts the browser host despite the internal bind hostname',async()=>expect((await POST(request('http://localhost:3492'))).status).toBe(400));
 it('rejects a foreign origin before any action',async()=>expect((await POST(request('https://elsewhere.example'))).status).toBe(403));
 it('rejects missing origins',async()=>expect((await POST(request())).status).toBe(403));
 it('rejects cross-site fetch metadata',async()=>expect((await POST(request('http://localhost:3492','cross-site'))).status).toBe(403));
});
